spring:
  cloud:
    gateway:
     discovery:
      
        locator:
          enabled: true
     routes:
      - id: SPRoom
        uri: lb://SPRoom
        predicates:
        - Path=/room/*
    
      - id: SPFood
        uri: http://localhost:8003
        predicates:
        - Path=/food/**
        
      - id: SPCustomer
        uri: http://localhost:8002
        predicates:
        - Path=/cust/** 